version: "3.0"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./tmp/apppostgres/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata