---
all:
  hosts:
    localhost:
      ansible_connection: local
    room1:
      ansible_host: 192.168.1.230
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /Users/aveiga/.ssh/id_rsa
    room2:
      ansible_host: 192.168.1.231
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /Users/aveiga/.ssh/id_rsa
